COPY SCRLOW.H \C\MYLIBS
IF NOT EXIST SCRLOW%1.C GOTO ASMFIL
BCC -c -mt -v- -O2 SCRLOW%1.C
TLIB \C\MYLIBS\SCRLOW_T -+SCRLOW%1
DEL SCRLOW%1.OBJ
BCC -c -ms -v- -O2 SCRLOW%1.C
TLIB \C\MYLIBS\SCRLOW_S -+SCRLOW%1
DEL SCRLOW%1.OBJ
BCC -c -mm -v- -O2 SCRLOW%1.C
TLIB \C\MYLIBS\SCRLOW_M -+SCRLOW%1
DEL SCRLOW%1.OBJ
BCC -c -mc -v- -O2 SCRLOW%1.C
TLIB \C\MYLIBS\SCRLOW_C -+SCRLOW%1
DEL SCRLOW%1.OBJ
BCC -c -ml -v- -O2 SCRLOW%1.C
TLIB \C\MYLIBS\SCRLOW_L -+SCRLOW%1
DEL SCRLOW%1.OBJ
BCC -c -mh -v- -O2 SCRLOW%1.C
TLIB \C\MYLIBS\SCRLOW_H -+SCRLOW%1
DEL SCRLOW%1.OBJ
GOTO END
:ASMFIL
TASM /m2/ml/dMDL=TINY    SCRLOW%1, SCRLOW%1
TLIB \C\MYLIBS\SCRLOW_T -+SCRLOW%1
DEL SCRLOW%1.OBJ
TASM /m2/ml/dMDL=SMALL   SCRLOW%1, SCRLOW%1
TLIB \C\MYLIBS\SCRLOW_S -+SCRLOW%1
DEL SCRLOW%1.OBJ
TASM /m2/ml/dMDL=MEDIUM  SCRLOW%1, SCRLOW%1
TLIB \C\MYLIBS\SCRLOW_M -+SCRLOW%1
DEL SCRLOW%1.OBJ
TASM /m2/ml/dMDL=COMPACT SCRLOW%1, SCRLOW%1
TLIB \C\MYLIBS\SCRLOW_C -+SCRLOW%1
DEL SCRLOW%1.OBJ
TASM /m2/ml/dMDL=LARGE   SCRLOW%1, SCRLOW%1
TLIB \C\MYLIBS\SCRLOW_L -+SCRLOW%1
DEL SCRLOW%1.OBJ
TASM /m2/ml/dMDL=HUGE    SCRLOW%1, SCRLOW%1
TLIB \C\MYLIBS\SCRLOW_H -+SCRLOW%1
DEL SCRLOW%1.OBJ
:END
DEL \C\MYLIBS\*.BAK
