CD \C\MYLIBS
COPY \C\SHHLIB\BASIC\BASIC.H
BCC -c -mt -v- -O2 \C\SHHLIB\BASIC\BASIC%1.C
TLIB SHHLIB_T -+BASIC%1
DEL BASIC%1.OBJ
BCC -c -ms -v- -O2 \C\SHHLIB\BASIC\BASIC%1.C
TLIB SHHLIB_S -+BASIC%1
DEL BASIC%1.OBJ
BCC -c -mm -v- -O2 \C\SHHLIB\BASIC\BASIC%1.C
TLIB SHHLIB_M -+BASIC%1
DEL BASIC%1.OBJ
BCC -c -mc -v- -O2 \C\SHHLIB\BASIC\BASIC%1.C
TLIB SHHLIB_C -+BASIC%1
DEL BASIC%1.OBJ
BCC -c -ml -v- -O2 \C\SHHLIB\BASIC\BASIC%1.C
TLIB SHHLIB_L -+BASIC%1
DEL BASIC%1.OBJ
BCC -c -mh -v- -O2 \C\SHHLIB\BASIC\BASIC%1.C
TLIB SHHLIB_H -+BASIC%1
DEL BASIC%1.OBJ
DEL *.BAK
CD \C\SHHLIB\BASIC
