;
; Konstanter som brukes av DIR-modulene og programmer som bruker disse.
;


  ;
  ; F›lgende lengder er beregnet † inkludere terminerende 0.
  ; Kompatible med Turbo C.
  ;
MAXPATH EQU     80      ; Maks lengde p† drv, dir, name, ext
MAXDRV  EQU     3       ; Maks lengde p† drive. "A:", 0
MAXDIR  EQU     66      ; Maks lengde p† directory
MAXNME  EQU     9       ; Maks lengde p† filnavn uten extension
MAXEXT  EQU     5       ; Maks lengde p† extension, inkludert "."


